name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - pandas
  - scipy
  - scikit-learn
  - tensorflow
  - tensorflow_datasets  
  - keras
